<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;

class ProductsSeeder extends Seeder
{
    public function run(): void
    {
        $cats   = Category::pluck('id', 'name');
        $brands = Brand::pluck('id', 'name');

        $smartphoneId  = $cats['Smartphones']  ?? null;
        $accessoryId   = $cats['Accessories']  ?? null;
        $tabletId      = $cats['Tablets']      ?? null;
        $earphoneId    = $cats['Earphones']    ?? null;
        $chargerId     = $cats['Chargers']     ?? null;

        $appleId    = $brands['Apple']   ?? null;
        $samsungId  = $brands['Samsung'] ?? null;
        $xiaomiId   = $brands['Xiaomi']  ?? null;
        $oneplusId  = $brands['OnePlus'] ?? null;

        $products = [
            // ─── Variable ────────────────────────────────────────────────────────────
            [
                'sku'               => 'IP15PM-BASE',
                'name'              => 'iPhone 15 Pro Max',
                'type'              => 'variable',
                'status'            => 'active',
                'category_id'       => $smartphoneId,
                'brand_id'          => $appleId,
                'short_description' => 'Titanium design with A17 Pro chip, 48MP camera system with 5× optical zoom, and USB 3 speeds.',
                'description'       => 'The iPhone 15 Pro Max is the pinnacle of Apple smartphone engineering. Built from aerospace-grade titanium and powered by the groundbreaking A17 Pro chip, it delivers extraordinary performance for every task from intensive gaming to 4K ProRes video editing. The 48MP main camera with a new 5× optical zoom telephoto lens captures stunning detail from far away, while the super-wide and macro lenses round out a versatile system. The 6.7-inch Super Retina XDR display with ProMotion and Always-On makes every scroll feel responsive. USB 3 speeds via the USB-C port let you transfer a 4K ProRes video in seconds.',
                'selling_price'     => 1199.00,
                'cost_price'        => 850.00,
                'compare_price'     => null,
                'stock_quantity'    => 0,
                'low_stock_threshold' => 3,
                'weight'            => 221,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => true,
                'published_at'      => now()->subDays(60),
            ],
            [
                'sku'               => 'IP15PL-BASE',
                'name'              => 'iPhone 15 Plus',
                'type'              => 'variable',
                'status'            => 'active',
                'category_id'       => $smartphoneId,
                'brand_id'          => $appleId,
                'short_description' => 'Big screen, all-day battery. iPhone 15 Plus with Dynamic Island, 48MP camera, and USB-C.',
                'description'       => 'iPhone 15 Plus gives you a lot to love. With the large 6.7-inch Super Retina XDR display and the power-efficient A16 Bionic chip, the battery life is extraordinary — lasting well beyond a full day of heavy use. The Dynamic Island draws your attention to important alerts and activities. The 48MP main camera captures incredible detail and the new 2× optical-quality zoom means you never miss a shot. And with USB-C, charging and data transfer just got a lot more convenient.',
                'selling_price'     => 899.00,
                'cost_price'        => 650.00,
                'compare_price'     => null,
                'stock_quantity'    => 0,
                'low_stock_threshold' => 3,
                'weight'            => 201,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => false,
                'published_at'      => now()->subDays(55),
            ],
            [
                'sku'               => 'SGS24U-BASE',
                'name'              => 'Samsung Galaxy S24 Ultra',
                'type'              => 'variable',
                'status'            => 'active',
                'category_id'       => $smartphoneId,
                'brand_id'          => $samsungId,
                'short_description' => 'Galaxy AI meets titanium frame with built-in S Pen and 200MP quad-camera system.',
                'description'       => 'Samsung Galaxy S24 Ultra redefines what a smartphone can do. Powered by Snapdragon 8 Gen 3 and Samsung\'s Galaxy AI, it offers real-time call translation, Chat Assist, and AI-powered photo editing directly on device. The 200MP main camera with 5× and 10× optical zoom lets you capture life\'s moments with professional clarity. The integrated S Pen is more precise than ever with near-zero latency. The titanium frame — lighter and stronger than previous generations — frames the 6.8-inch Dynamic AMOLED 2X display with a 120Hz adaptive refresh rate.',
                'selling_price'     => 1299.00,
                'cost_price'        => 900.00,
                'compare_price'     => 1399.00,
                'stock_quantity'    => 0,
                'low_stock_threshold' => 3,
                'weight'            => 232,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => true,
                'published_at'      => now()->subDays(50),
            ],
            [
                'sku'               => 'SGS24-BASE',
                'name'              => 'Samsung Galaxy S24',
                'type'              => 'variable',
                'status'            => 'active',
                'category_id'       => $smartphoneId,
                'brand_id'          => $samsungId,
                'short_description' => 'Compact flagship with Galaxy AI, Snapdragon 8 Gen 3, and 50MP triple camera in your pocket.',
                'description'       => 'Samsung Galaxy S24 is the everyday flagship that punches far above its compact size. The Snapdragon 8 Gen 3 delivers blazing performance with excellent thermal efficiency, while Galaxy AI brings circle-to-search, note assist, and real-time translation straight to your fingertips. The flat 6.2-inch Dynamic AMOLED 2X display is easy to hold and use one-handed. The 50MP main camera with OIS, a 12MP ultra-wide, and a 10MP 3× telephoto cover virtually every shooting scenario.',
                'selling_price'     => 849.00,
                'cost_price'        => 600.00,
                'compare_price'     => null,
                'stock_quantity'    => 0,
                'low_stock_threshold' => 3,
                'weight'            => 167,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => false,
                'published_at'      => now()->subDays(48),
            ],
            [
                'sku'               => 'XM14P-BASE',
                'name'              => 'Xiaomi 14 Pro',
                'type'              => 'variable',
                'status'            => 'active',
                'category_id'       => $smartphoneId,
                'brand_id'          => $xiaomiId,
                'short_description' => 'Leica professional optics meets Snapdragon 8 Gen 3 and HyperCharge 120W in Xiaomi\'s flagship.',
                'description'       => 'Xiaomi 14 Pro is a flagship built around the camera. Co-engineered with Leica, it features a 50MP Light Fusion 900 sensor with a 1" equivalent size — one of the largest in the industry — capable of capturing extraordinary detail in low light. Snapdragon 8 Gen 3 ensures every interaction is instantaneous. The 6.73-inch LTPO AMOLED display adjusts from 1 to 120Hz dynamically to save battery. And when you need to recharge, 120W HyperCharge takes the battery from 0 to 100% in under 20 minutes.',
                'selling_price'     => 749.00,
                'cost_price'        => 520.00,
                'compare_price'     => 799.00,
                'stock_quantity'    => 0,
                'low_stock_threshold' => 3,
                'weight'            => 223,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => false,
                'published_at'      => now()->subDays(40),
            ],
            [
                'sku'               => 'OP12-BASE',
                'name'              => 'OnePlus 12',
                'type'              => 'variable',
                'status'            => 'active',
                'category_id'       => $smartphoneId,
                'brand_id'          => $oneplusId,
                'short_description' => '100W SUPERVOOC, Hasselblad-tuned triple cameras, and buttery-smooth 120Hz AMOLED display.',
                'description'       => 'OnePlus 12 is speed — in every sense. The legendary 100W SUPERVOOC charging fills the 5400mAh battery in just 25 minutes, while 50W AIRVOOC wireless charging means you can top up mid-meeting without a cable. The Hasselblad-tuned camera system with a 50MP periscope telephoto delivers images with natural colour science and precise tonal mapping. Snapdragon 8 Gen 3 and up to 16GB RAM ensure lag is a distant memory. The 6.82-inch 2K AMOLED ProXDR display is simply stunning.',
                'selling_price'     => 749.00,
                'cost_price'        => 500.00,
                'compare_price'     => null,
                'stock_quantity'    => 0,
                'low_stock_threshold' => 3,
                'weight'            => 220,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => false,
                'published_at'      => now()->subDays(35),
            ],
            [
                'sku'               => 'IPPM4-BASE',
                'name'              => 'iPad Pro 13" M4',
                'type'              => 'variable',
                'status'            => 'active',
                'category_id'       => $tabletId,
                'brand_id'          => $appleId,
                'short_description' => 'Ultra Retina XDR OLED display, M4 chip, and Apple Pencil Pro in the thinnest iPad ever made.',
                'description'       => 'iPad Pro 13" with M4 is the most advanced iPad Apple has ever made. At just 5.1mm, it is also the thinnest Apple product ever. The stunning 13-inch Ultra Retina XDR OLED display offers 1000 nits of full-screen brightness, 1600 nits peak, and true blacks for an unprecedented visual experience. M4 chip — with a 10-core CPU and up to 16-core GPU — makes this the most powerful iPad ever, capable of running Final Cut Pro and Logic Pro with ease. Support for Apple Pencil Pro and the new landscape front camera make it perfect for professionals.',
                'selling_price'     => 1299.00,
                'cost_price'        => 900.00,
                'compare_price'     => null,
                'stock_quantity'    => 0,
                'low_stock_threshold' => 2,
                'weight'            => 579,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => true,
                'published_at'      => now()->subDays(30),
            ],
            [
                'sku'               => 'IPAM2-BASE',
                'name'              => 'iPad Air 11" M2',
                'type'              => 'variable',
                'status'            => 'active',
                'category_id'       => $tabletId,
                'brand_id'          => $appleId,
                'short_description' => 'Liquid Retina display, M2 chip, and compatibility with Apple Pencil Pro and Magic Keyboard Folio.',
                'description'       => 'iPad Air 11" with M2 delivers powerful performance in a thin and light design. The vivid 11-inch Liquid Retina display with True Tone, P3 wide colour, and anti-reflective coating makes your content look stunning. The M2 chip — the same chip as in the 2022 MacBook Pro — handles demanding apps like Procreate and LumaFusion smoothly. Works with Apple Pencil Pro and the redesigned Magic Keyboard, making it a compelling laptop replacement for students and creatives.',
                'selling_price'     => 699.00,
                'cost_price'        => 480.00,
                'compare_price'     => null,
                'stock_quantity'    => 0,
                'low_stock_threshold' => 3,
                'weight'            => 462,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => false,
                'published_at'      => now()->subDays(28),
            ],
            [
                'sku'               => 'SGBU3P-BASE',
                'name'              => 'Samsung Galaxy Buds3 Pro',
                'type'              => 'variable',
                'status'            => 'active',
                'category_id'       => $earphoneId,
                'brand_id'          => $samsungId,
                'short_description' => 'Intelligent ANC, 360 Audio with Dolby Head Tracking, and up to 30 hours total battery life.',
                'description'       => 'Galaxy Buds3 Pro deliver a premium audio experience from every angle. Intelligent Active Noise Cancellation adapts in real time to your environment, muting the world around you when you need focus. 360 Audio with Dolby Head Tracking creates an immersive soundstage that follows your head movements. The redesigned blade tip and open-type design sit comfortably in your ear all day. With up to 6 hours of playback per charge and a further 24 hours from the compact case, you\'re covered from morning commute to evening workout.',
                'selling_price'     => 199.00,
                'cost_price'        => 130.00,
                'compare_price'     => 229.00,
                'stock_quantity'    => 0,
                'low_stock_threshold' => 5,
                'weight'            => 18,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => false,
                'published_at'      => now()->subDays(25),
            ],
            [
                'sku'               => 'MSFLC15-BASE',
                'name'              => 'MagSafe Leather Case iPhone 15',
                'type'              => 'variable',
                'status'            => 'active',
                'category_id'       => $accessoryId,
                'brand_id'          => $appleId,
                'short_description' => 'Premium full-grain leather MagSafe case designed to age beautifully and protect perfectly.',
                'description'       => 'The Apple MagSafe Leather Case is crafted from specially tanned and finished European leather that feels great in hand and develops a natural patina over time. The interior has a soft microfiber lining to protect your iPhone. Built-in magnets align perfectly with MagSafe chargers and accessories, so you never have to remove the case. Precise cutouts for speakers, Lightning connector, and camera mean no compromises in function. It fits snugly on iPhone 15 while adding minimal bulk.',
                'selling_price'     => 59.00,
                'cost_price'        => 18.00,
                'compare_price'     => null,
                'stock_quantity'    => 0,
                'low_stock_threshold' => 5,
                'weight'            => 38,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => false,
                'published_at'      => now()->subDays(20),
            ],
            [
                'sku'               => 'SCIP15-BASE',
                'name'              => 'Silicone Case iPhone 15',
                'type'              => 'variable',
                'status'            => 'active',
                'category_id'       => $accessoryId,
                'brand_id'          => $appleId,
                'short_description' => 'Soft-touch silicone with built-in MagSafe, microfiber lining, and precise cutouts for iPhone 15.',
                'description'       => 'Apple Silicone Case provides a clean look, comfortable feel, and excellent protection. The silky, soft-touch finish and flexible form factor ensure a secure grip and a slim profile. The interior is lined with soft microfiber to protect your iPhone. Built-in magnets align perfectly with MagSafe chargers and accessories for a seamless wireless charging experience. Available in a range of rich colours to match your personal style.',
                'selling_price'     => 49.00,
                'cost_price'        => 12.00,
                'compare_price'     => null,
                'stock_quantity'    => 0,
                'low_stock_threshold' => 5,
                'weight'            => 30,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => false,
                'published_at'      => now()->subDays(18),
            ],

            // ─── Simple ──────────────────────────────────────────────────────────────
            [
                'sku'               => 'APL-30WUSBC',
                'name'              => 'Apple 30W USB-C Charger',
                'type'              => 'simple',
                'status'            => 'active',
                'category_id'       => $chargerId,
                'brand_id'          => $appleId,
                'short_description' => 'Charge iPhone to 50% in around 30 minutes with USB Power Delivery technology.',
                'description'       => 'The Apple 30W USB-C Power Adapter offers fast, efficient charging at home, in the office, or on the go. Pair it with the USB-C to MagSafe 3 Cable (sold separately) to charge MacBook Air quickly and safely. It also works with iPad Pro, iPad Air, AirPods, and any other USB-C device. The compact folding design makes it ideal for travel.',
                'selling_price'     => 49.00,
                'cost_price'        => 28.00,
                'compare_price'     => null,
                'stock_quantity'    => 120,
                'low_stock_threshold' => 10,
                'weight'            => 56,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => false,
                'published_at'      => now()->subDays(90),
            ],
            [
                'sku'               => 'SAM-45WCHG',
                'name'              => 'Samsung 45W Super Fast Charger 2.0',
                'type'              => 'simple',
                'status'            => 'active',
                'category_id'       => $chargerId,
                'brand_id'          => $samsungId,
                'short_description' => '45W Programmable Power Supply charges Galaxy S24 Ultra from 0% to 70% in just 30 minutes.',
                'description'       => 'Samsung 45W Super Fast Charging 2.0 adapter uses Programmable Power Supply (PPS) technology to deliver optimal power levels throughout the charging cycle, extending battery longevity compared to conventional fast chargers. The slim, rectangular design fits neatly in a bag or pocket. Compatible with all Samsung Galaxy devices that support Super Fast Charging as well as any USB-PD device.',
                'selling_price'     => 39.99,
                'cost_price'        => 24.00,
                'compare_price'     => null,
                'stock_quantity'    => 85,
                'low_stock_threshold' => 10,
                'weight'            => 65,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => false,
                'published_at'      => now()->subDays(85),
            ],
            [
                'sku'               => 'ANK-65WGAN',
                'name'              => 'Anker 65W GaN USB-C Charger',
                'type'              => 'simple',
                'status'            => 'active',
                'category_id'       => $chargerId,
                'brand_id'          => null,
                'short_description' => 'Single-port 65W GaN charger. Charges laptops, phones, and tablets at full speed in a compact design.',
                'description'       => 'Anker PowerPort III 65W charges all your USB-C devices at full speed from a single compact adapter thanks to GaN (Gallium Nitride) technology. It\'s 50% smaller than the original 61W Apple charger yet delivers the same 65W of power. The PowerIQ 3.0 with PPS negotiates the optimal voltage and current for every device, whether it\'s an iPhone, Android phone, iPad, or MacBook.',
                'selling_price'     => 39.99,
                'cost_price'        => 22.00,
                'compare_price'     => 49.99,
                'stock_quantity'    => 95,
                'low_stock_threshold' => 10,
                'weight'            => 70,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => false,
                'published_at'      => now()->subDays(80),
            ],
            [
                'sku'               => 'APL-MSAFCHG',
                'name'              => 'Apple MagSafe Charger 15W',
                'type'              => 'simple',
                'status'            => 'active',
                'category_id'       => $chargerId,
                'brand_id'          => $appleId,
                'short_description' => 'Perfectly aligns with iPhone for faster 15W wireless charging without removing your MagSafe case.',
                'description'       => 'The Apple MagSafe Charger connects magnetically to iPhone 15, iPhone 14, and iPhone 13 models to deliver faster wireless charging up to 15W — three times faster than standard Qi chargers. The built-in magnets ensure perfect alignment every time so you never have to fidget to find the charging sweet spot. The 1m braided USB-C cable allows flexible positioning on your nightstand or desk.',
                'selling_price'     => 39.00,
                'cost_price'        => 22.00,
                'compare_price'     => null,
                'stock_quantity'    => 60,
                'low_stock_threshold' => 8,
                'weight'            => 24,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => false,
                'published_at'      => now()->subDays(75),
            ],
            [
                'sku'               => 'GEN-USBC2M',
                'name'              => 'USB-C to USB-C Cable 2m Braided',
                'type'              => 'simple',
                'status'            => 'active',
                'category_id'       => $accessoryId,
                'brand_id'          => null,
                'short_description' => '240W capable braided nylon USB-C to USB-C cable with 10Gbps data transfer speeds.',
                'description'       => 'This premium braided nylon USB-C to USB-C cable supports 240W of power delivery for laptop-class charging and 10Gbps data transfer speeds via USB 3.2 Gen 2. The braided exterior resists tangling and is rated for over 30,000 bends. 2-metre length gives plenty of reach whether you\'re at a desk or on the sofa. Compatible with MacBook, iPad, iPhone 15, Samsung Galaxy, and any other USB-C device.',
                'selling_price'     => 14.99,
                'cost_price'        => 4.50,
                'compare_price'     => null,
                'stock_quantity'    => 200,
                'low_stock_threshold' => 20,
                'weight'            => 45,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => false,
                'published_at'      => now()->subDays(70),
            ],
            [
                'sku'               => 'ANK-100WGAN4P',
                'name'              => 'Anker 100W 4-Port GaN Charger',
                'type'              => 'simple',
                'status'            => 'active',
                'category_id'       => $chargerId,
                'brand_id'          => null,
                'short_description' => 'Charge four devices simultaneously with 100W total output — two USB-C plus two USB-A ports.',
                'description'       => 'Anker 547 Charger (100W) replaces four single-port chargers with one compact GaN desktop hub. The two USB-C ports share up to 100W intelligently — 60W + 40W or 100W single port — while the two USB-A ports each supply up to 12W. ActiveShield 2.0 monitors temperature 3 million times per day and adjusts output accordingly to protect your devices. A 1.5m braided power cable is included.',
                'selling_price'     => 69.99,
                'cost_price'        => 40.00,
                'compare_price'     => 89.99,
                'stock_quantity'    => 45,
                'low_stock_threshold' => 5,
                'weight'            => 130,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => true,
                'published_at'      => now()->subDays(65),
            ],
            [
                'sku'               => 'GEN-TG-IP15',
                'name'              => 'Tempered Glass Screen Protector iPhone 15',
                'type'              => 'simple',
                'status'            => 'active',
                'category_id'       => $accessoryId,
                'brand_id'          => null,
                'short_description' => '9H hardness, 99% optical clarity, touch precision identical to bare glass, and easy bubble-free install.',
                'description'       => 'This premium tempered glass screen protector is precision-cut for iPhone 15 and uses Case-Friendly edges to work with most protective cases. The 9H-rated glass is 30 times stronger than regular plastic film and maintains perfect touch sensitivity. An oleophobic coating resists fingerprints and smudges. The self-aligning installation tray makes the application process foolproof — just peel, align, and press.',
                'selling_price'     => 14.99,
                'cost_price'        => 3.50,
                'compare_price'     => null,
                'stock_quantity'    => 300,
                'low_stock_threshold' => 30,
                'weight'            => 35,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => false,
                'published_at'      => now()->subDays(60),
            ],
            [
                'sku'               => 'GEN-RGHLD',
                'name'              => 'Universal Phone Ring Holder Stand',
                'type'              => 'simple',
                'status'            => 'active',
                'category_id'       => $accessoryId,
                'brand_id'          => null,
                'short_description' => '360° rotating ring stand for any flat-back phone. MagSafe-case compatible with anti-slip adhesive.',
                'description'       => 'This ultra-thin phone ring holder provides a secure finger loop for one-handed use while doubling as a kickstand for watching videos in landscape or portrait. The 360° rotation ring and 180° adjustable foot let you prop your phone at any angle on a flat surface. The premium 3M adhesive pad sticks firmly to any flat-back case without leaving residue when removed. Slim enough to slide into your pocket without a bump.',
                'selling_price'     => 9.99,
                'cost_price'        => 2.50,
                'compare_price'     => null,
                'stock_quantity'    => 500,
                'low_stock_threshold' => 50,
                'weight'            => 20,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => false,
                'published_at'      => now()->subDays(55),
            ],
            [
                'sku'               => 'GEN-20KPB65W',
                'name'              => '20000mAh Power Bank PD 65W',
                'type'              => 'simple',
                'status'            => 'active',
                'category_id'       => $chargerId,
                'brand_id'          => null,
                'short_description' => '65W USB-C PD keeps your laptop going all day and charges iPhone 15 from flat to full over 4 times.',
                'description'       => 'This compact 20,000mAh power bank is the last charger you\'ll need to pack for a long trip. A single USB-C port delivers 65W of Power Delivery output, enough to charge a 13" MacBook from 0% to 50% in about an hour. The 20Wh capacity will charge an iPhone 15 roughly 4.5 times. A USB-A port provides 18W Quick Charge for older devices simultaneously. The built-in LED indicator shows remaining capacity at a glance, and recharging the bank itself at 65W takes under 2.5 hours.',
                'selling_price'     => 59.99,
                'cost_price'        => 32.00,
                'compare_price'     => 79.99,
                'stock_quantity'    => 60,
                'low_stock_threshold' => 8,
                'weight'            => 440,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => true,
                'published_at'      => now()->subDays(45),
            ],
            [
                'sku'               => 'GEN-CARWC15W',
                'name'              => 'Car Wireless Charger 15W',
                'type'              => 'simple',
                'status'            => 'active',
                'category_id'       => $accessoryId,
                'brand_id'          => null,
                'short_description' => 'MagSafe-compatible 15W car mount that holds and fast-charges your iPhone hands-free while driving.',
                'description'       => 'This car wireless charger combines a secure vent mount with 15W MagSafe-compatible wireless charging. Strong magnets hold your iPhone firmly in place even over rough roads, while the Qi2 15W output delivers fast charging without needing to plug in. The 360° ball-joint adjusts to any viewing angle. Powered via the included USB-C cable that connects to any car USB-C port or adapter. Compatible with iPhone 12 and later with a MagSafe case.',
                'selling_price'     => 29.99,
                'cost_price'        => 13.00,
                'compare_price'     => null,
                'stock_quantity'    => 80,
                'low_stock_threshold' => 10,
                'weight'            => 85,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => false,
                'published_at'      => now()->subDays(40),
            ],
            [
                'sku'               => 'APL-MSPOPS',
                'name'              => 'Apple MagSafe PopSocket',
                'type'              => 'simple',
                'status'            => 'active',
                'category_id'       => $accessoryId,
                'brand_id'          => $appleId,
                'short_description' => 'Official MagSafe-integrated PopSocket grip that perfectly aligns and secures to any MagSafe iPhone.',
                'description'       => 'PopSockets PopGrip for MagSafe combines the convenience of MagSafe with the grip and stand functionality of PopSockets. The base features built-in magnets that align perfectly with MagSafe-compatible iPhones and cases for a satisfying click and secure hold. The collapsible accordion mechanism extends for a grip or stand, then clicks flat again for wireless charging. The top is swappable — pop it off and replace it with any standard PopTop.',
                'selling_price'     => 29.99,
                'cost_price'        => 12.00,
                'compare_price'     => null,
                'stock_quantity'    => 120,
                'low_stock_threshold' => 15,
                'weight'            => 28,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => false,
                'published_at'      => now()->subDays(35),
            ],
            [
                'sku'               => 'BLK-3IN1PAD',
                'name'              => 'Belkin BoostCharge Pro 3-in-1',
                'type'              => 'simple',
                'status'            => 'active',
                'category_id'       => $chargerId,
                'brand_id'          => null,
                'short_description' => 'Charge iPhone, AirPods, and Apple Watch simultaneously on a single MagSafe-certified charging pad.',
                'description'       => 'Belkin BoostCharge Pro 3-in-1 is Apple-certified for MagSafe and delivers 15W fast wireless charging to iPhone 14 and 15 models while simultaneously charging AirPods on the 5W Qi pad and Apple Watch on the dedicated magnetic puck. The soft silicone mat prevents devices from sliding. A single 20W USB-C cable keeps your desk clean. Supports iPhone 12 and later, all AirPods with wireless charging, and all Apple Watch models.',
                'selling_price'     => 79.99,
                'cost_price'        => 48.00,
                'compare_price'     => 99.99,
                'stock_quantity'    => 35,
                'low_stock_threshold' => 5,
                'weight'            => 195,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => true,
                'published_at'      => now()->subDays(30),
            ],
            [
                'sku'               => 'SAM-TABS10U',
                'name'              => 'Samsung Galaxy Tab S10 Ultra',
                'type'              => 'simple',
                'status'            => 'active',
                'category_id'       => $tabletId,
                'brand_id'          => $samsungId,
                'short_description' => '14.6-inch Dynamic AMOLED 2X display, Snapdragon 8 Gen 3, Galaxy AI, and S Pen all included.',
                'description'       => 'Samsung Galaxy Tab S10 Ultra is the definitive Android tablet for productivity and creativity. The enormous 14.6-inch Dynamic AMOLED 2X display with 120Hz and 2960×1848 resolution renders every detail with stunning accuracy. Snapdragon 8 Gen 3 and 12GB of RAM ensure smooth multitasking across split-screen apps. The included S Pen connects magnetically and charges wirelessly from the tablet — always there when you need it. Galaxy AI brings Note Assist, PDF translation, and transcript summaries right to your workflow.',
                'selling_price'     => 1099.00,
                'cost_price'        => 840.00,
                'compare_price'     => null,
                'stock_quantity'    => 20,
                'low_stock_threshold' => 3,
                'weight'            => 718,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => false,
                'published_at'      => now()->subDays(22),
            ],
            [
                'sku'               => 'XMI-RN13PP',
                'name'              => 'Xiaomi Redmi Note 13 Pro+',
                'type'              => 'simple',
                'status'            => 'active',
                'category_id'       => $smartphoneId,
                'brand_id'          => $xiaomiId,
                'short_description' => '200MP camera, 120W HyperCharge, and Dimensity 7200 Ultra in a premium curved-edge design.',
                'description'       => 'Xiaomi Redmi Note 13 Pro+ proves that a world-class camera and lightning-fast charging don\'t have to cost a fortune. The 200MP OmniVision sensor captures extraordinary detail, whether you\'re shooting in broad daylight or a dimly lit restaurant. 120W HyperCharge fills the 5000mAh battery in just 19 minutes — a full charge during a short coffee break. The 6.67-inch curved 1.5K AMOLED display with 120Hz feels premium in every swipe. Dimensity 7200 Ultra handles gaming and multitasking without breaking a sweat.',
                'selling_price'     => 399.00,
                'cost_price'        => 270.00,
                'compare_price'     => null,
                'stock_quantity'    => 55,
                'low_stock_threshold' => 8,
                'weight'            => 204,
                'weight_unit'       => 'g',
                'is_active'         => true,
                'is_featured'       => false,
                'published_at'      => now()->subDays(15),
            ],
        ];

        foreach ($products as $data) {
            $name = $data['name'];
            $sku  = $data['sku'];

            $existing = Product::where('name', $name)->first();

            if (!$existing) {
                Product::create($data);
            } else {
                // Update everything except sku/barcode to avoid unique constraint conflicts
                $existing->update(Arr::except($data, ['sku', 'barcode']));
            }
        }
    }
}
