import {
  LayoutDashboard, ShoppingCart, Package, Tag, Award, Users, History,
  Warehouse, Store, UserCircle, ShieldCheck, Truck, ClipboardList,
  RotateCcw, RefreshCw, TrendingDown, LayoutList, Settings, Settings2, Home,
  BarChart2, DollarSign, FileText, Box, Grid, Layers, ChevronRight,
  Star, Globe, Bell, HelpCircle, BookOpen, PieChart, Activity,
  Database, Lock, Eye, Edit, Trash2, Plus, Search, Filter, Download,
  Upload, ArrowLeft, ArrowRight, Check, X, Menu, Percent,
  Scissors, Shirt, KanbanSquare, Receipt,
} from "lucide-react";

export const iconMap = {
  LayoutDashboard,
  ShoppingCart,
  Package,
  Tag,
  Award,
  Users,
  History,
  Warehouse,
  Store,
  UserCircle,
  ShieldCheck,
  Truck,
  ClipboardList,
  RotateCcw,
  RefreshCw,
  TrendingDown,
  LayoutList,
  Settings,
  Settings2,
  Home,
  BarChart2,
  DollarSign,
  FileText,
  Box,
  Grid,
  Layers,
  ChevronRight,
  Star,
  Globe,
  Bell,
  HelpCircle,
  BookOpen,
  PieChart,
  Activity,
  Database,
  Lock,
  Eye,
  Edit,
  Trash2,
  Plus,
  Search,
  Filter,
  Download,
  Upload,
  ArrowLeft,
  ArrowRight,
  Check,
  X,
  Menu,
  Percent,
  Scissors,
  Shirt,
  KanbanSquare,
  Receipt,
};

export const iconNames = Object.keys(iconMap).sort();

export function getIcon(name) {
  return iconMap[name] ?? Settings;
}
